### PR TITLE
Makefile

### PR DESCRIPTION
**Pull request by bambuchaAdm**
From script to makefile

### CODE REVIEW

**Comment by ktoso** [comment]
Please add asciidoctor to what should I have in order to contribute. :-)

**Comment by ktoso** [comment]
Will merge right away then.

**Comment by bambuchaAdm** [comment]
Ruby and make are only requirements from system. All stuff is managed by bundler. 
You doesn't need install asciidoctor manually.

**Comment by ktoso** [comment]
Seems good, merging

**Pull request merged**
