### PR TITLE
Fix some more typos, clean up the TODO

### PR DESCRIPTION
**Pull request by michalrus**
I didn't notice the `TODO` before. =)

(It seems that `index.html` hasn't yet been automatically regenerated?)

### CODE REVIEW

**Comment by ktoso** [comment]
Merge z samolotu ;-)

**Comment by michalrus** [comment]
^-^

**Comment by ktoso** [comment]
Index generuje ręcznie. Będzie dziś

**Comment by ktoso** [comment]
Published update - thanks again!

**Pull request merged**
