### PR TITLE
Create section about case class.

### PR DESCRIPTION
**Pull request by bambuchaAdm**

### CODE REVIEW

**Comment by ktoso** [comment]
Needs some updates, are you up to it Łukasz? :-)

**Comment by bambuchaAdm** [comment]
Case you can see, yes :-)

**Comment by ktoso** [comment]
Hm, needs some slight wording / style fixes, but I think I'll pull it in and fix a bit - is that ok with you? :-)

**Comment by bambuchaAdm** [comment]
Ok no problem.

**Comment by ktoso** [comment]
Pulled in, will have to refactor a bit :-)
Thanks!

**Pull request closed without merging**
