### PR TITLE
language edits

### PR DESCRIPTION
**Pull request by phderome**
contributing.md: I had to do extra step do install bundle, so I added a line for that in the original 3 steps.

wording and minor typesetting changes here and there (there are lots, so it may be long to review, but I made them in good faith for interest of readers). I might have a few content related questions here or there if time allows.

### CODE REVIEW

**Comment by ktoso** [comment]
Wow, thanks a ton, these are awesome improvements :)

**Comment by phderome** [comment]
Someone just tweeted today about rewriting http://docs.scala-lang.org/tutorials/tour/tour-of-scala.html so I am glad I could help in small way.

**Comment by phderome** [comment]
You have yet to push it to the target [site](http://ktoso.github.io/scala-types-of-types/), it seems.

**Comment by ktoso** [comment]
Have not had the time yet, traveling and meetings, will get to it, don't worry 😉

**Pull request merged**
